name: React Internet Notifier CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run EsLint
        run: yarn run lint

      - name: Run UnitTest
        run: yarn run test

      - name: Run Build
        run: yarn run build
